# This is an example configuration
[network]
bind = "127.0.0.1"
port = 25565
compression_threshold = 256

[server_info]
motd = "Some demo MOTD"
priorities = ["some_server"]

[players]
type = "Constant"
players = 1337
max_players = 200
fail_on_over_join = true

[[server]]
name = "some_server"
ip = "127.0.0.1"
port = 25566
forwarding_mode = { type = "Velocity", forwarding_secret = "secret" }
